return {
    -- "williamboman/mason.nvim",
    -- dependencies = { "WhoIsSethDaniel/mason-tool-installer.nvim" },
    -- config = function()
    --   require("mason").setup({
    --     ui = {
    --       border = "rounded",
    --       icons = {
    --         package_installed = "✓",
    --         package_pending = "➜",
    --         package_uninstalled = "✗",
    --       },
    --     },
    --     PATH = "prepend",
    --     log_level = vim.log.levels.INFO,
    --     max_concurrent_installers = 8, -- Increased for faster installs
    --   })
    --
    --   require("mason-tool-installer").setup({
    --     ensure_installed = {
    --       -- Formatters only, since LSP servers are handled by mason-lspconfig
    --       "prettier",
    --       "black",
    --       "isort",
    --       "stylua",
    --       "shfmt",
    --     },
    --     auto_update = true,
    --     run_on_start = true,
    --   })
    -- end,
}
